apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels:
   name: nginx-pod       
spec: 
  containers: 
  - name: nginx
    image: nginx:1.14.0       
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
  volumes:
  - name: data
    hostPath:
      path: "/data/app"
    
